#!/usr/bin/env python3
"""gen_rom_layout.py — generate the pinned-address veneer layer of the
synthetic BLE/LC3 ROM stub (ticket 0028).

Inputs:
  --lds FILE...    ROM symbol maps (name = 0xADDR; one per line).  The
                   addresses are the ABI: the firmware BLs straight into
                   them.
  --impl FILE      List of implemented stub entry points, one symbol per
                   line, each of which exists in the stub objects as
                   `hstub_<symbol>` (produced by `nm` in the Makefile).

Outputs:
  --veneers FILE   GNU as source: one 4-byte `b.w` veneer at every pinned
                   address.  Implemented symbols branch to their
                   `hstub_<symbol>`; everything else branches to a
                   generated trap thunk that reports symbol index + caller
                   LR to the emulator doorbell device and returns
                   GAP_ERR_NOT_SUPPORTED.
  --syms FILE      "<idx> <hex-addr> <name>" per line, indexed in address
                   order — loaded by the QEMU doorbell device to print
                   human-readable trap reports.

The veneer section is emitted with `.org` paddings relative to the lowest
pinned address; the linker script places it at that address.
"""

import argparse
import re
import sys


def parse_lds(paths):
    syms = {}
    rx = re.compile(r"^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(0x[0-9a-fA-F]+)\s*;")
    for path in paths:
        with open(path) as f:
            for line in f:
                m = rx.match(line)
                if not m:
                    continue
                name, addr = m.group(1), int(m.group(2), 16)
                # Thumb bit: the map carries odd (Thumb) addresses; code
                # placement uses the even address.
                syms[name] = addr & ~1
    return sorted(syms.items(), key=lambda kv: kv[1])


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--lds", nargs="+", required=True)
    ap.add_argument("--impl", required=True)
    ap.add_argument("--veneers", required=True)
    ap.add_argument("--syms", required=True)
    args = ap.parse_args()

    syms = parse_lds(args.lds)
    if not syms:
        sys.exit("gen_rom_layout: no symbols parsed")

    with open(args.impl) as f:
        implemented = {line.strip() for line in f if line.strip()}

    known = {name for name, _ in syms}
    orphans = implemented - known
    if orphans:
        sys.exit(f"gen_rom_layout: hstub_ implementations with no pinned "
                 f"symbol: {sorted(orphans)}")

    base = syms[0][1]
    prev_end = None
    out = []
    out.append("/* Generated by gen_rom_layout.py — do not edit. */")
    out.append(".syntax unified")
    out.append(".thumb")
    out.append("")
    out.append('.section .romvec, "ax", %progbits')
    for name, addr in syms:
        off = addr - base
        if prev_end is not None and off < prev_end:
            sys.exit(f"gen_rom_layout: overlapping veneer at {name} "
                     f"({addr:#x}) — previous symbol needs {prev_end - off} "
                     f"more bytes")
        out.append(f".org {off:#x}")
        out.append(f".global {name}")
        out.append(f".thumb_func")
        out.append(f"{name}:")
        if name in implemented:
            out.append(f"\tb.w hstub_{name}")
        else:
            out.append(f"\tb.w __trap_{name}")
        prev_end = off + 4
    out.append("")

    # Trap thunks: movw r12, #idx ; b.w rom_stub_trap_entry (8 bytes each)
    out.append('.section .text.traps, "ax", %progbits')
    for idx, (name, _addr) in enumerate(syms):
        if name in implemented:
            continue
        out.append(f".thumb_func")
        out.append(f"__trap_{name}:")
        out.append(f"\tmovw r12, #{idx}")
        out.append(f"\tb.w rom_stub_trap_entry")
    out.append("")

    with open(args.veneers, "w") as f:
        f.write("\n".join(out))

    with open(args.syms, "w") as f:
        for idx, (name, addr) in enumerate(syms):
            f.write(f"{idx} {addr:#x} {name}\n")

    n_impl = sum(1 for name, _ in syms if name in implemented)
    print(f"gen_rom_layout: {len(syms)} pinned symbols "
          f"({n_impl} implemented, {len(syms) - n_impl} trapped), "
          f"veneer base {base:#x}")


if __name__ == "__main__":
    main()
